FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install make \
                    g++ \
                    libncurses5-dev \
                    libssl-dev \
                    openssl \
                    libnet1-dev \
                    libpcap0.8-dev \
                    libsctp-dev

